package ejerciciostabla.exportacionjava;

import java.io.Serializable;
import java.sql.Blob;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of Asignaturas.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Asignaturas implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** Num_asig. */
	private Blob numAsig;

	/** Nombre. */
	private String nombre;

	/** Profesores. */
	private Profesores profesores;

	/** The set of Cursan. */
	private Set<Cursan> cursanSet;

	/**
	 * Constructor.
	 */
	public Asignaturas() {
		this.cursanSet = new HashSet<Cursan>();
	}

	/**
	 * Set the Num_asig.
	 * 
	 * @param numAsig
	 *            Num_asig
	 */
	public void setNumAsig(Blob numAsig) {
		this.numAsig = numAsig;
	}

	/**
	 * Get the Num_asig.
	 * 
	 * @return Num_asig
	 */
	public Blob getNumAsig() {
		return this.numAsig;
	}

	/**
	 * Set the Nombre.
	 * 
	 * @param nombre
	 *            Nombre
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * Get the Nombre.
	 * 
	 * @return Nombre
	 */
	public String getNombre() {
		return this.nombre;
	}

	/**
	 * Set the Profesores.
	 * 
	 * @param profesores
	 *            Profesores
	 */
	public void setProfesores(Profesores profesores) {
		this.profesores = profesores;
	}

	/**
	 * Get the Profesores.
	 * 
	 * @return Profesores
	 */
	public Profesores getProfesores() {
		return this.profesores;
	}

	/**
	 * Set the set of the Cursan.
	 * 
	 * @param cursanSet
	 *            The set of Cursan
	 */
	public void setCursanSet(Set<Cursan> cursanSet) {
		this.cursanSet = cursanSet;
	}

	/**
	 * Add the Cursan.
	 * 
	 * @param cursan
	 *            Cursan
	 */
	public void addCursan(Cursan cursan) {
		this.cursanSet.add(cursan);
	}

	/**
	 * Get the set of the Cursan.
	 * 
	 * @return The set of Cursan
	 */
	public Set<Cursan> getCursanSet() {
		return this.cursanSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((numAsig == null) ? 0 : numAsig.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Asignaturas other = (Asignaturas) obj;
		if (numAsig == null) {
			if (other.numAsig != null) {
				return false;
			}
		} else if (!numAsig.equals(other.numAsig)) {
			return false;
		}
		return true;
	}

}
